// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzK3ByOagKw9Lhtn5AJSPsWwP93kgybY',
    appId: '1:981939546325:web:95d2f1041eb3cf5bd55a5c',
    messagingSenderId: '981939546325',
    projectId: 'flutter-test-3e378',
    authDomain: 'flutter-test-3e378.firebaseapp.com',
    storageBucket: 'flutter-test-3e378.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrewSztnUhbdD5hbOnoQ-rQ8VasyYoqw0',
    appId: '1:981939546325:android:f23a23fbba00c518d55a5c',
    messagingSenderId: '981939546325',
    projectId: 'flutter-test-3e378',
    storageBucket: 'flutter-test-3e378.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsqfr5IIA3biYy68-3Xl15QPyHhfX2deM',
    appId: '1:981939546325:ios:0d5270c57eabebffd55a5c',
    messagingSenderId: '981939546325',
    projectId: 'flutter-test-3e378',
    storageBucket: 'flutter-test-3e378.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsqfr5IIA3biYy68-3Xl15QPyHhfX2deM',
    appId: '1:981939546325:ios:0d5270c57eabebffd55a5c',
    messagingSenderId: '981939546325',
    projectId: 'flutter-test-3e378',
    storageBucket: 'flutter-test-3e378.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOzK3ByOagKw9Lhtn5AJSPsWwP93kgybY',
    appId: '1:981939546325:web:319f1dbaa3b56f63d55a5c',
    messagingSenderId: '981939546325',
    projectId: 'flutter-test-3e378',
    authDomain: 'flutter-test-3e378.firebaseapp.com',
    storageBucket: 'flutter-test-3e378.appspot.com',
  );

}